#!/usr/bin/env bash

# all warnings: on
set -euo pipefail


# root (sudo check)
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root. Please run with sudo."
    exit 1
fi


source /etc/os-release #sets the source so that we can use the variables in said file


#-----------OS DETECTION------------
PKG_MANAGER=""

if [[ $ID == "arch" || $ID == "manjaro" || $ID == "endeavouros" || $ID == "cachyos" ]]; then
    PKG_MANAGER="pacman"
    echo "Arch based system detected"
elif [[ $ID == "ubuntu" || $ID == "debian" || $ID == "mint" ]]; then
    PKG_MANAGER="apt"
    echo "Ubuntu/Debian based system detected"
else
    echo "Unsupported OS detected. Exiting."
    exit 1
fi

#----------DEPENDENCY CHECKING, CURL, JQ, TMUX, and JAVA---------

for item in curl jq tmux; do
    if ! command -v "$item" &> /dev/null; then
       if [[ $PKG_MANAGER == "pacman" ]]; then
            echo "$item is not installed. Installing with pacman..."
            pacman -S --noconfirm "$item"
        elif [[ $PKG_MANAGER == "apt" ]]; then
            echo "$item is not installed. Installing with apt..."
            apt update && apt install -y "$item"
        fi
    else
        echo "$item is already installed"
    fi
done

#--Java check--

if ! command -v java &> /dev/null; then
    echo "Java is not installed. Installing Java 21 with $PKG_MANAGER..."
    if [[ $PKG_MANAGER == "pacman" ]]; then
        pacman -S --noconfirm jdk21-openjdk
    elif [[ $PKG_MANAGER == "apt" ]]; then
        apt update && apt install -y openjdk-21-jre-headless
    fi
    if ! command -v java &> /dev/null; then
        echo "Java installation failed. Please install Java 21 manually and re-run the script."
        exit 1
    fi
    echo "Java installed successfully."
else
    echo "Java is already installed, proceeding with setup..."
fi

#----------INSTALL DIRECTORY------------
read -rp "Enter installation directory (def: /home/$USER/minecraft-server): " INSTALL_DIR
INSTALL_DIR=${INSTALL_DIR:-/home/$USER/minecraft-server}

if [[ -d "$INSTALL_DIR" ]]; then
    echo "Installation directory exists: $INSTALL_DIR"
    read -rp "Directory already exists. Continue anyway? [y/N]: " cont
    if [[ ! "$cont" =~ ^[Yy]$ ]]; then
        echo "Exiting..."
        exit 1
    fi
else
    echo "Creating installation directory: $INSTALL_DIR"
    mkdir -p "$INSTALL_DIR"
fi

#---------MINECRAFT SERVER JAR DOWNLOAD------------

# read -rp "Enter Minecraft server version (def: latest): " MC_VERSION

#getting the latest version of minecraft server from the manifest
MANIFEST=$(curl -fsSL "https://launchermeta.mojang.com/mc/game/version_manifest.json")
LATEST_VERSION=$(echo "$MANIFEST" | jq -r '.latest.release')
VERSION_URL=$(echo "$MANIFEST" | jq -r --arg v "$LATEST_VERSION" '.versions[] | select(.id == $v) | .url')

#getting the download url for the server jar
DOWNLOAD_URL=$(curl -fsSL "$VERSION_URL" | jq -r '.downloads.server.url')
curl -fsSL "$DOWNLOAD_URL" -o "$INSTALL_DIR/server.jar"

#---------SERVER CONFIGURATION------------
echo "eula=true" > $INSTALL_DIR/eula.txt

echo "SERVER CONFIGURATION STARTING..."

read -rp "Enter max players (def: 20): " MAX_PLAYERS
MAX_PLAYERS=${MAX_PLAYERS:-20}
read -rp "Enter server port (def: 25565): " SERVER_PORT
SERVER_PORT=${SERVER_PORT:-25565}
read -rp "Enter server MOTD (def: Welcome to my Minecraft Server!): " MOTD
MOTD=${MOTD:-Welcome to my Minecraft Server!}
read -rp "Enter server difficulty (peaceful-easy-normal-hard) (def: easy): " DIFFICULTY
DIFFICULTY=${DIFFICULTY:-easy}
read -rp "Enter server game mode (survival-creative-adventure-spectator) (def: survival): " GAME_MODE
GAME_MODE=${GAME_MODE:-survival}
read -rp "Enable whitelist? [y/N]: " WHITELIST
WHITELIST_ENABLE=${WHITELIST:-N}

cat > "$INSTALL_DIR/server.properties" <<EOL
#Minecraft server properties
#Generated by mc-server-kit
accepts-transfers=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=$DIFFICULTY
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=$GAME_MODE
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=$MAX_PLAYERS
max-tick-time=60000
max-world-size=29999984
motd=$MOTD
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=60
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=$SERVER_PORT
simulation-distance=10
spawn-monsters=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=$([[ $WHITELIST =~ ^[Yy]$ ]] && echo "true" || echo "false")
EOL

echo "SERVER CONFIGURATION COMPLETE."


#---------TMUX (CREATION OF SERVER START SCRIPT)------------

read -rp "Enter tmux session name (def: mc-server): " TMUX_SESSION
TMUX_SESSION=${TMUX_SESSION:-mc-server}
read -rp "Enter minimum RAM allocation (def: 1G): " MIN_RAM
MIN_RAM=${MIN_RAM:-1G}
read -rp "Enter maximum RAM allocation (def: 2G): " MAX_RAM
MAX_RAM=${MAX_RAM:-2G}

cat > "$INSTALL_DIR/start.sh" <<EOL
#!/usr/bin/env bash
cd "$INSTALL_DIR"
tmux new-session -d -s "$TMUX_SESSION" "java -Xms$MIN_RAM -Xmx$MAX_RAM -jar server.jar nogui"
echo "Server started. Attach with tmux attach-session -t $TMUX_SESSION"
EOL

chmod +x "$INSTALL_DIR/start.sh"


echo "-----------------------------------"
echo "Setup complete!"
echo "Server installed to: $INSTALL_DIR"
echo "To start your server: cd $INSTALL_DIR && bash start.sh"
echo "To attach to console: tmux attach -t $TMUX_SESSION"
echo "To detach (keep running): Ctrl+B then D"
echo "-----------------------------------"